### ISSUE TITLE
2 Issue, Spicord not load & Error Starting

### ISSUE THREAD

**Issue by LoneDevilX** [Spicord/Spicord#33]
**1st Issue:**
Regenerating spicord folder when starting:
https://pastebin.ubuntu.com/p/4kp4vNHt8z/

**2nd Issue:**
I used old spicord folder (same Ver.) with config= **[DELETED BECAUSE TOKEN EXPOSED]**
Error when start:
https://pastebin.ubuntu.com/p/crrgd6NYMg/

**Comment by OopsieWoopsie** [comment]
Hi, I have modified your message to remove the link to your config, go to the Discord Developer Panel and generate a new token for your bot, otherwise a token-scraper may get your token and **destroy your whole discord server**.

Regarding the first issue, I have no idea why have that happened, maybe that was due your Java version (unsupported TLS version) or a firewall had blocked the download.
And about the second issue I have also no idea why would Toml try to parse a comment as something that is not a comment, probably your file encoding? Delete the config file and then restart the server to have a new and clean config, then make sure to edit it on your computer (do not use the text editor _(notepad)_ that comes with Windows!), or if your Multicraft panel allows you to edit files, then try to use that editor.
